title: TextStyles
description: ""
header_text: ""
footer_text: Copyright 2020 Malachi Martin
header_feature_image: ../uploads/istockphoto-1141677781-170667a.jpg
bannerheight: 10vmax
logo: ../uploads/blog-logo.png
favicon: ../uploads/blog-logo.png
gridlayout: false
fixednavbar: false
upzoom: true
