title: TextStyles
description: ""
header_text: Typography Blog
footer_text: Copyright 2020 Malachi Martin
header_feature_image: ""
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
