title: TextStyles
description: ""
header_text: ""
footer_text: Copyright 2020 Malachi Martin
header_feature_image: ../uploads/movie-clapper-board-130297.png
bannerheight: 10vmax
logo: ../uploads/blog-logo.png
favicon: ../uploads/blog-logo.png
gridlayout: false
fixednavbar: false
upzoom: true
